import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

const callAutoTable = (doc: jsPDF, options: any) => {
  try {
    (doc as any).autoTable(options);
  } catch (e) {
    autoTable(doc, options);
  }
};

interface CompanySettings {
  companyName: string;
  address: string;
  logoUrl?: string;
  gstNumber?: string;
  panNumber?: string;
  poTerms?: string;
  boqTerms?: string;
  currencySymbol?: string;
}

interface POItem {
  description: string;
  quantity: number;
  unit: string;
  rate: number;
  gstRate: number;
  gstAmount: number;
  total: number;
  item?: {
    name: string;
  };
}

interface POData {
  poNumber: string;
  vendor: {
    name?: string;
    address?: string;
    email?: string;
    gstNumber?: string;
  };
  project?: {
    name: string;
  };
  boq?: {
    name: string;
    project?: {
      name: string;
    };
  };
  items: POItem[];
  subTotal: number;
  gstAmount: number;
  totalAmount: number;
  terms?: string;
  createdAt?: string;
}

interface BOQItem {
  description: string;
  quantity: number;
  unit: string;
  rate: number;
  gstRate: number;
  gstAmount: number;
  amount: number;
}

interface BOQData {
  title: string;
  client: {
    name: string;
    email: string;
  };
  lineItems: BOQItem[];
  subTotal: number;
  gstAmount: number;
  totalValue: number;
  createdAt: string;
}

export const generatePOPDF = (po: POData, settings: CompanySettings) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;
  const primary: [number, number, number] = [79, 70, 229];
  const slate900: [number, number, number] = [15, 23, 42];
  const slate500: [number, number, number] = [100, 116, 139];
  const border: [number, number, number] = [226, 232, 240];
  const surface: [number, number, number] = [248, 250, 252];
  const currencySymbol = settings.currencySymbol || '₹';
  const marginX = 15;
  const gap = 10;
  const headerH = 26;

  const formatAmount = (value: number) => `${currencySymbol} ${(value || 0).toFixed(2)}`;
  const safeText = (value: any) => (value === null || value === undefined ? '' : String(value));
  const dateText = (value?: string) => {
    try {
      if (!value) return new Date().toLocaleDateString();
      const d = new Date(value);
      return Number.isNaN(d.getTime()) ? new Date().toLocaleDateString() : d.toLocaleDateString();
    } catch {
      return new Date().toLocaleDateString();
    }
  };

  const drawTopBar = (rightValue: string, subtitle: string) => {
    doc.setFillColor(primary[0], primary[1], primary[2]);
    doc.rect(0, 0, pageWidth, headerH, 'F');
    doc.setTextColor(255, 255, 255);

    let logoPlaced = false;
    if (settings.logoUrl && settings.logoUrl.length > 10) {
      try {
        const imgData = settings.logoUrl;
        const format = imgData.includes('jpeg') || imgData.includes('jpg') ? 'JPEG' : 'PNG';
        doc.addImage(imgData, format, marginX, 5, 16, 16);
        logoPlaced = true;
      } catch {
        logoPlaced = false;
      }
    }

    const titleX = logoPlaced ? marginX + 20 : marginX;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.text(safeText(settings.companyName || 'Company'), titleX, 11);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.text(subtitle, titleX, 18);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.text(rightValue, pageWidth - marginX, 14, { align: 'right' });
  };

  const drawFooter = (pageNumber: number) => {
    doc.setTextColor(slate500[0], slate500[1], slate500[2]);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.text(`Generated by ${safeText(settings.companyName || 'ERP System')}`, marginX, pageHeight - 10);
    doc.text(`Page ${pageNumber}`, pageWidth - marginX, pageHeight - 10, { align: 'right' });
  };

  const drawInfoBox = (x: number, y: number, w: number, h: number, title: string, lines: { label: string; value: string }[]) => {
    doc.setDrawColor(border[0], border[1], border[2]);
    doc.setFillColor(surface[0], surface[1], surface[2]);
    (doc as any).roundedRect ? (doc as any).roundedRect(x, y, w, h, 3, 3, 'FD') : doc.rect(x, y, w, h, 'FD');

    doc.setTextColor(primary[0], primary[1], primary[2]);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.text(title, x + 8, y + 10);

    let currentY = y + 18;
    const maxLineW = w - 16;
    doc.setFontSize(9);
    for (const row of lines) {
      if (currentY > y + h - 8) break;
      doc.setTextColor(slate500[0], slate500[1], slate500[2]);
      doc.setFont('helvetica', 'bold');
      doc.text(row.label, x + 8, currentY);
      doc.setTextColor(slate900[0], slate900[1], slate900[2]);
      doc.setFont('helvetica', 'normal');
      const valueLines = doc.splitTextToSize(row.value || '-', maxLineW - 42);
      doc.text(valueLines, x + 52, currentY);
      currentY += Math.max(6, valueLines.length * 5);
    }
  };

  const poNumber = safeText(po.poNumber || 'PO');
  drawTopBar(poNumber, 'Purchase Order');

  doc.setTextColor(slate500[0], slate500[1], slate500[2]);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  const issuerAddress = safeText(settings.address || '').replace(/\s+/g, ' ').trim();
  const issuerAddressLine = issuerAddress ? (doc.splitTextToSize(issuerAddress, pageWidth - marginX * 2 - 70)[0] || '') : '';
  const issuerRight = [settings.gstNumber ? `GSTIN: ${settings.gstNumber}` : '', settings.panNumber ? `PAN: ${settings.panNumber}` : ''].filter(Boolean).join('   |   ');
  if (issuerAddressLine) doc.text(issuerAddressLine, marginX, headerH + 10);
  if (issuerRight) doc.text(issuerRight, pageWidth - marginX, headerH + 10, { align: 'right' });

  const metaY = headerH + 16;
  const boxW = (pageWidth - marginX * 2 - gap) / 2;
  const boxH = 54;

  const vendorName = safeText(po.vendor?.name || 'N/A');
  const vendorAddress = safeText(po.vendor?.address || '');
  const vendorEmail = safeText(po.vendor?.email || 'N/A');
  const vendorGstin = safeText(po.vendor?.gstNumber || '');
  const vendorSummaryParts = [vendorName, vendorAddress].filter(Boolean);

  drawInfoBox(marginX, metaY, boxW, boxH, 'Vendor', [
    { label: 'Name', value: vendorName },
    { label: 'Email', value: vendorEmail },
    ...(vendorGstin ? [{ label: 'GSTIN', value: vendorGstin }] : []),
    ...(vendorSummaryParts.length > 1 ? [{ label: 'Address', value: vendorAddress }] : []),
  ]);

  const projectName = safeText(po.project?.name || po.boq?.project?.name || po.boq?.name || 'N/A');
  drawInfoBox(marginX + boxW + gap, metaY, boxW, boxH, 'Order', [
    { label: 'PO No', value: poNumber },
    { label: 'Date', value: dateText(po.createdAt) },
    { label: 'Project', value: projectName },
  ]);

  doc.setTextColor(slate900[0], slate900[1], slate900[2]);

  const tableStartY = metaY + boxH + 12;

  const tableData = (po.items || []).map((item, index) => {
    const qty = item.quantity || 0;
    const rate = item.rate || 0;
    const amountExclGst = qty * rate;
    const description = safeText(item.description || (item.item && item.item.name) || 'No Description');
    return [
      index + 1,
      description,
      qty,
      item.unit || 'Nos',
      rate.toFixed(2),
      amountExclGst.toFixed(2),
      `${item.gstRate || 0}%`,
      (item.gstAmount || 0).toFixed(2),
      (item.total || 0).toFixed(2)
    ];
  });

  callAutoTable(doc, {
    startY: tableStartY,
    margin: { left: marginX, right: marginX, top: headerH + 16, bottom: 20 },
    head: [['#', 'Description', 'Qty', 'Unit', 'Rate', 'Amount', 'GST %', 'GST Amount', 'Total']],
    body: tableData,
    theme: 'grid',
    headStyles: { fillColor: primary, textColor: 255, fontStyle: 'bold', halign: 'center', valign: 'middle' },
    styles: { fontSize: 8.5, cellPadding: 3, textColor: slate900 },
    columnStyles: {
      0: { cellWidth: 8 },
      1: { cellWidth: 'auto' },
      2: { cellWidth: 12, halign: 'center' },
      3: { cellWidth: 12, halign: 'center' },
      4: { cellWidth: 20, halign: 'right' },
      5: { cellWidth: 22, halign: 'right' },
      6: { cellWidth: 12, halign: 'center' },
      7: { cellWidth: 20, halign: 'right' },
      8: { cellWidth: 22, halign: 'right' }
    },
    didDrawPage: (data: any) => {
      drawTopBar(poNumber, 'Purchase Order');
      if (data.pageNumber > 1) {
        doc.setTextColor(slate500[0], slate500[1], slate500[2]);
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8.5);
        if (issuerAddressLine) doc.text(issuerAddressLine, marginX, headerH + 10);
        if (issuerRight) doc.text(issuerRight, pageWidth - marginX, headerH + 10, { align: 'right' });
      }
      drawFooter(data.pageNumber);
    },
  });

  const finalY = (doc as any).lastAutoTable?.finalY || 150;

  let cursorY = finalY + 10;
  const totalsBoxW = 78;
  const totalsBoxH = 34;
  const totalsBoxX = pageWidth - marginX - totalsBoxW;
  if (cursorY + totalsBoxH > pageHeight - 20) {
    doc.addPage();
    drawTopBar(poNumber, 'Purchase Order');
    drawFooter(doc.getNumberOfPages());
    cursorY = headerH + 20;
  }

  doc.setDrawColor(border[0], border[1], border[2]);
  doc.setFillColor(surface[0], surface[1], surface[2]);
  (doc as any).roundedRect ? (doc as any).roundedRect(totalsBoxX, cursorY, totalsBoxW, totalsBoxH, 3, 3, 'FD') : doc.rect(totalsBoxX, cursorY, totalsBoxW, totalsBoxH, 'FD');
  doc.setTextColor(slate500[0], slate500[1], slate500[2]);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.text('Subtotal', totalsBoxX + 8, cursorY + 12);
  doc.text('GST', totalsBoxX + 8, cursorY + 19);
  doc.setTextColor(slate900[0], slate900[1], slate900[2]);
  doc.setFont('helvetica', 'normal');
  doc.text(formatAmount(po.subTotal || 0), totalsBoxX + totalsBoxW - 8, cursorY + 12, { align: 'right' });
  doc.text(formatAmount(po.gstAmount || 0), totalsBoxX + totalsBoxW - 8, cursorY + 19, { align: 'right' });
  doc.setDrawColor(border[0], border[1], border[2]);
  doc.line(totalsBoxX + 8, cursorY + 23, totalsBoxX + totalsBoxW - 8, cursorY + 23);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10.5);
  doc.text('Total', totalsBoxX + 8, cursorY + 31);
  doc.text(formatAmount(po.totalAmount || 0), totalsBoxX + totalsBoxW - 8, cursorY + 31, { align: 'right' });

  cursorY += totalsBoxH + 10;

  const termsToDisplay = po.terms || settings.poTerms;
  if (termsToDisplay) {
    const termsTitleY = cursorY;
    const termsTextY = termsTitleY + 8;
    const maxTermsW = pageWidth - marginX * 2;
    doc.setTextColor(primary[0], primary[1], primary[2]);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.text('Terms & Conditions', marginX, termsTitleY);

    doc.setTextColor(slate900[0], slate900[1], slate900[2]);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    const termsLines = doc.splitTextToSize(safeText(termsToDisplay), maxTermsW);
    const estimatedH = termsLines.length * 5 + 10;
    if (termsTextY + estimatedH > pageHeight - 20) {
      doc.addPage();
      drawTopBar(poNumber, 'Purchase Order');
      drawFooter(doc.getNumberOfPages());
      cursorY = headerH + 20;
      doc.setTextColor(primary[0], primary[1], primary[2]);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.text('Terms & Conditions', marginX, cursorY);
      doc.setTextColor(slate900[0], slate900[1], slate900[2]);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.text(termsLines, marginX, cursorY + 8);
    } else {
      doc.text(termsLines, marginX, termsTextY);
    }
  }

  doc.save(`${po.poNumber || 'PO'}_${new Date().getTime()}.pdf`);
};

export const generateBOQPDF = (boq: BOQData, settings: CompanySettings) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;
  const primary: [number, number, number] = [79, 70, 229];
  const slate900: [number, number, number] = [15, 23, 42];
  const slate500: [number, number, number] = [100, 116, 139];
  const border: [number, number, number] = [226, 232, 240];
  const surface: [number, number, number] = [248, 250, 252];
  const currencySymbol = settings.currencySymbol || '₹';
  const marginX = 15;
  const gap = 10;
  const headerH = 26;

  const formatAmount = (value: number) => `${currencySymbol} ${(value || 0).toFixed(2)}`;
  const safeText = (value: any) => (value === null || value === undefined ? '' : String(value));
  const dateText = (value?: string) => {
    try {
      if (!value) return new Date().toLocaleDateString();
      const d = new Date(value);
      return Number.isNaN(d.getTime()) ? new Date().toLocaleDateString() : d.toLocaleDateString();
    } catch {
      return new Date().toLocaleDateString();
    }
  };

  const drawTopBar = (rightValue: string, subtitle: string) => {
    doc.setFillColor(primary[0], primary[1], primary[2]);
    doc.rect(0, 0, pageWidth, headerH, 'F');
    doc.setTextColor(255, 255, 255);

    let logoPlaced = false;
    if (settings.logoUrl && settings.logoUrl.length > 10) {
      try {
        const imgData = settings.logoUrl;
        const format = imgData.includes('jpeg') || imgData.includes('jpg') ? 'JPEG' : 'PNG';
        doc.addImage(imgData, format, marginX, 5, 16, 16);
        logoPlaced = true;
      } catch {
        logoPlaced = false;
      }
    }

    const titleX = logoPlaced ? marginX + 20 : marginX;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.text(safeText(settings.companyName || 'Company'), titleX, 11);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.text(subtitle, titleX, 18);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.text(rightValue, pageWidth - marginX, 14, { align: 'right' });
  };

  const drawFooter = (pageNumber: number) => {
    doc.setTextColor(slate500[0], slate500[1], slate500[2]);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.text(`Generated by ${safeText(settings.companyName || 'ERP System')}`, marginX, pageHeight - 10);
    doc.text(`Page ${pageNumber}`, pageWidth - marginX, pageHeight - 10, { align: 'right' });
  };

  const drawInfoBox = (x: number, y: number, w: number, h: number, title: string, lines: { label: string; value: string }[]) => {
    doc.setDrawColor(border[0], border[1], border[2]);
    doc.setFillColor(surface[0], surface[1], surface[2]);
    (doc as any).roundedRect ? (doc as any).roundedRect(x, y, w, h, 3, 3, 'FD') : doc.rect(x, y, w, h, 'FD');

    doc.setTextColor(primary[0], primary[1], primary[2]);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.text(title, x + 8, y + 10);

    let currentY = y + 18;
    const maxLineW = w - 16;
    doc.setFontSize(9);
    for (const row of lines) {
      if (currentY > y + h - 8) break;
      doc.setTextColor(slate500[0], slate500[1], slate500[2]);
      doc.setFont('helvetica', 'bold');
      doc.text(row.label, x + 8, currentY);
      doc.setTextColor(slate900[0], slate900[1], slate900[2]);
      doc.setFont('helvetica', 'normal');
      const valueLines = doc.splitTextToSize(row.value || '-', maxLineW - 42);
      doc.text(valueLines, x + 52, currentY);
      currentY += Math.max(6, valueLines.length * 5);
    }
  };

  const boqTitle = safeText(boq.title || 'BOQ');
  drawTopBar(boqTitle, 'Bill of Quantities');

  doc.setTextColor(slate500[0], slate500[1], slate500[2]);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  const issuerAddress = safeText(settings.address || '').replace(/\s+/g, ' ').trim();
  const issuerAddressLine = issuerAddress ? (doc.splitTextToSize(issuerAddress, pageWidth - marginX * 2 - 70)[0] || '') : '';
  const issuerRight = [settings.gstNumber ? `GSTIN: ${settings.gstNumber}` : '', settings.panNumber ? `PAN: ${settings.panNumber}` : ''].filter(Boolean).join('   |   ');
  if (issuerAddressLine) doc.text(issuerAddressLine, marginX, headerH + 10);
  if (issuerRight) doc.text(issuerRight, pageWidth - marginX, headerH + 10, { align: 'right' });

  const metaY = headerH + 16;
  const boxW = (pageWidth - marginX * 2 - gap) / 2;
  const boxH = 46;

  drawInfoBox(marginX, metaY, boxW, boxH, 'Client', [
    { label: 'Name', value: safeText(boq.client?.name || 'N/A') },
    { label: 'Email', value: safeText(boq.client?.email || 'N/A') },
  ]);

  drawInfoBox(marginX + boxW + gap, metaY, boxW, boxH, 'BOQ', [
    { label: 'Title', value: boqTitle },
    { label: 'Date', value: dateText(boq.createdAt) },
  ]);

  const tableStartY = metaY + boxH + 12;

  const tableData = (boq.lineItems || []).map((item, index) => [
    index + 1,
    item.description || 'No Description',
    item.quantity || 0,
    item.unit || 'Nos',
    (item.rate || 0).toFixed(2),
    ((item.quantity || 0) * (item.rate || 0)).toFixed(2),
    `${item.gstRate || 0}%`,
    (item.gstAmount || 0).toFixed(2),
    (item.amount || 0).toFixed(2)
  ]);

  callAutoTable(doc, {
    startY: tableStartY,
    margin: { left: marginX, right: marginX, top: headerH + 16, bottom: 20 },
    head: [['#', 'Description', 'Qty', 'Unit', 'Rate', 'Amount', 'GST %', 'GST Amount', 'Total']],
    body: tableData,
    theme: 'grid',
    headStyles: { fillColor: primary, textColor: 255, fontStyle: 'bold', halign: 'center', valign: 'middle' },
    styles: { fontSize: 8.5, cellPadding: 3, textColor: slate900 },
    didDrawPage: (data: any) => {
      drawTopBar(boqTitle, 'Bill of Quantities');
      if (data.pageNumber > 1) {
        doc.setTextColor(slate500[0], slate500[1], slate500[2]);
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8.5);
        if (issuerAddressLine) doc.text(issuerAddressLine, marginX, headerH + 10);
        if (issuerRight) doc.text(issuerRight, pageWidth - marginX, headerH + 10, { align: 'right' });
      }
      drawFooter(data.pageNumber);
    },
  });

  const finalY = (doc as any).lastAutoTable?.finalY || 150;

  let cursorY = finalY + 10;
  const totalsBoxW = 78;
  const totalsBoxH = 34;
  const totalsBoxX = pageWidth - marginX - totalsBoxW;
  if (cursorY + totalsBoxH > pageHeight - 20) {
    doc.addPage();
    drawTopBar(boqTitle, 'Bill of Quantities');
    drawFooter(doc.getNumberOfPages());
    cursorY = headerH + 20;
  }

  doc.setDrawColor(border[0], border[1], border[2]);
  doc.setFillColor(surface[0], surface[1], surface[2]);
  (doc as any).roundedRect ? (doc as any).roundedRect(totalsBoxX, cursorY, totalsBoxW, totalsBoxH, 3, 3, 'FD') : doc.rect(totalsBoxX, cursorY, totalsBoxW, totalsBoxH, 'FD');
  doc.setTextColor(slate500[0], slate500[1], slate500[2]);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.text('Subtotal', totalsBoxX + 8, cursorY + 12);
  doc.text('GST', totalsBoxX + 8, cursorY + 19);
  doc.setTextColor(slate900[0], slate900[1], slate900[2]);
  doc.setFont('helvetica', 'normal');
  doc.text(formatAmount(boq.subTotal || 0), totalsBoxX + totalsBoxW - 8, cursorY + 12, { align: 'right' });
  doc.text(formatAmount(boq.gstAmount || 0), totalsBoxX + totalsBoxW - 8, cursorY + 19, { align: 'right' });
  doc.setDrawColor(border[0], border[1], border[2]);
  doc.line(totalsBoxX + 8, cursorY + 23, totalsBoxX + totalsBoxW - 8, cursorY + 23);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10.5);
  doc.text('Total', totalsBoxX + 8, cursorY + 31);
  doc.text(formatAmount(boq.totalValue || 0), totalsBoxX + totalsBoxW - 8, cursorY + 31, { align: 'right' });

  doc.save(`${boq.title || 'BOQ'}_${new Date().getTime()}.pdf`);
};
